##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_pod
description: A package offering tools to manage app state using ValueListenable objects called Pods.
version: 0.14.2
repository: https://github.com/robmllze/df_pod
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - bloc
  - provider
  - redux
  - riverpod
  - state-management

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  df_type: ^0.6.2
  df_cleanup: ^0.3.2

  shared_preferences: ^2.3.2
  tuple: ^2.0.2
  equatable: ^2.0.5
  meta: ^1.15.0

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: ^5.0.0
  df_log: ^0.2.2
